# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/thlorenz/doctoc
    rev: v2.1.0
    hooks:
      - id: doctoc
#-   repo: https://github.com/pre-commit/mirrors-prettier
#    rev: v2.4.1
#    hooks:
#    -   id: prettier
#        additional_dependencies:
#          - prettier@2.1.2
#          - "@prettier/plugin-xml@0.12.0"
